### ISSUE TITLE
forward_kinematics method , joints values

### ISSUE THREAD

**Issue by hugosciascia** [Phylliade/ikpy#107]
Hello everyone, thank you for those powerfull tool !

There is something strange I do not understand with your forward_kinematics method for an armChain (from URDF file).

I have a 6 DOF robot, why I have to put 7 values for the joints parameters ? There is only 6 joints rights ? So I have to set one to 0 ?

I do not understand because I try to verify that with Webots and the results only maths for [0]*7 (no moving joints).

Thanks !

**Comment by Phylliade** [comment]
Actually your chain has an additional root joint, which is the basis of your robot and anchors your first link. Without it, you won't consider the first link when doing tbe FK.
It cannot move so the rotation angle is set to 0.

Regarding your issue with your robot, this is likely  not related to this first link, but to your URDF file.
Since the FK is deterministic, the issue cannot be on the IKPy side
