### ISSUE TITLE
Prismatic joint works as revolute one

### ISSUE THREAD

**Issue by smandyscom** [Phylliade/ikpy#28]
Hi , i created a following URDF

```
<robot
  name="flat">
  <link
    name="base_link">
  </link>
  <link
    name="U_shape">
  </link>
  <joint
    name="m1"
    type="prismatic">
    <origin
      xyz="10 0 0"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="U_shape" />
    <axis
      xyz="1 0 0" />
  </joint>
</robot> 
```

When trying to do chain.forward_kinematic , it outputs this:

command 
`my_chain.forward_kinematics([0,10],True)`

output
```
array([[  1.        ,   0.        ,   0.        ,  10.        ],
       [  0.        ,  -0.83907153,   0.54402111,   0.        ],
       [  0.        ,  -0.54402111,  -0.83907153,   0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]])
```

seems it rotates about X-axis, but translate from X-axis was expected.
Is prismatic joint supported ? thanks.

**Comment by Phylliade** [comment]
Hi smandyscom, prismatic joints are currently not supported out of the box. But, internally, everything is set up in order to support them : the internal structure of the library can handle prismatic joints with no changes.
Actually, it only requires to add the syntax for the prismatic joints to the [URDF parser](https://github.com/Phylliade/ikpy/blob/master/src/ikpy/URDF_utils.py#L15-L44), and you should be ready to go!
