### ISSUE TITLE
Hi, any tutorials ? 

### ISSUE THREAD

**Issue by helxsz** [Phylliade/ikpy#29]
I am working on the [Dobot robotic arm](http://dobot.cc/dobot-armv1/product-overview.html), how would I get started on the library, do you have any tutorials to begin with ?

**Comment by Phylliade** [comment]
Hi @helxsz,
Yes, there are many ressources!
As described on the front page, there is a [notebook](https://github.com/Phylliade/ikpy/blob/master/tutorials/ikpy/Quickstart.ipynb) to quickstart, and a [wiki](https://github.com/Phylliade/ikpy/wiki) to go deeper into the library and its capabilities.
Note that you don't need anything to run the tutorials, since it will only plot the kinematic chains, or simulate a [poppy](https://www.poppy-project.org/en/) robot.

To use the Dobot arm, you would have to create an URDF file for the robot. (It's not that hard, but requires some time.)
